//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dreamcometotruenetService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DreamCategory
    {
        public int DreamCateID { get; set; }
        public string DreamCateName { get; set; }
        public Nullable<bool> IsEnable { get; set; }
    }
}
