//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dreamcometotruenetService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFinance
    {
        public string UserName { get; set; }
        public decimal MonthlyIncome { get; set; }
        public decimal MonthlyExpenses { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
